- name: configur mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Install mysql libraries
    ansible.builtin.pip: # ansible pip module
      name: PyMySQL
      executable: pip3.9 # To know present version of ansible- "ansible --version"

  - name: Install mysql server
    ansible.builtin.package: # ansible package module
      name: mysql-server
      state: installed

  - name: start and enable mysql
    ansible.builtin.service: # ansible start and enable service
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info: # ansible mysql module- mysql_info module
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.poojari.store
    register: mysql_info
    ignore_errors: true  # "ansible error handling" . In this we get error and we are telling that ignor it.

  - name: print the output
    ansible.builtin.debug:
      msg: "mysql information: {{ mysql_info }}" 